

spring:
  security:
    basic:
      enable: true   # 开启基于HTTP basic的认证
    user:            # 配置用户的账号信息
      name: chenxihua
      password: 123456
  application:
    name: eureka-server
eureka:
  server:
    enable-self-preservation: false     # 关闭自我保护   其实有自我保护，挺好的。不建议关闭。有一篇文章有介绍： https://blog.csdn.net/hellozpc/article/details/83692496#commentBox
    eviction-interval-timer-in-ms: 5000 # 清理服务器的时间间隔
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # 是否将自己注册到Eureka服务中,因为该应用本身就是注册中心，不需要再注册自己（集群的时候为true）
    fetch-registry: false    # 是否从Eureka中获取注册信息,因为自己为注册中心,不会在该应用中的检索服务信息
    service-url:
      defaultZone: http://localhost:8760/eureka/
server:
  port: 8760
feign:
  httpclient:
    connection-timeout: 30000

