server:
  port: 8761   # 开启多个端口， port: 8661.  zuul已经默认开启了负载均衡。
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true     # 将自己的ip地址注册到Eureka服务中
    instance-id: ${spring.application.name}###${server.port}    # 指定实例id
  client:
    service-url:    # 使用账号密码注册到eureka中
      defaultZone: http://chenxihua:123456@localhost:8760/eureka/
    register-with-eureka: true        # 因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    fetch-registry: true              # 是否需要从eureka上检索服务
spring:
  application:
    name: producer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    open-in-view: true
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        hbm2ddl:
          auto: update
